println("Enter a Positive Integer")
var number = readInt()
println("Enter a string")
var string = readLine()
println(number)
println(number % 3)
println(scala.math.pow(number, 3).toInt)
println(scala.math.log10(number))
println(string)
println(string.substring(string.length - 3, string.length))
println(string(2).toInt)
//println(string(0))
println(string.replaceAll(string(0).toString,"@"))

